const express = require('express')
const app = express()
require("./connection")
app.use(express.json())
app.use(express.urlencoded({extended: true}))
const appRoutes = require("./routes/appRoutes")
const apiRoutes = require("./routes/apiRoutes")
const path = require("path")
app.use(appRoutes)
app.use(apiRoutes)
app.use(express.static( "public"))
const connection = require('./connection')
app.listen(3000, function(){
    console.log('server running')
})